name: plugins_coder-workspace-release

on:
  release:
    types:
      - created
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: false

      - name: Clone Gerrit source
        run: |
          git clone https://gerrit.googlesource.com/gerrit gerrit-src
          echo "GERRIT_DIR=$(pwd)/gerrit-src" >> $GITHUB_ENV

      - name: Initialize Gerrit submodules
        working-directory: ${{ env.GERRIT_DIR }}
        run: |
          git submodule sync --recursive
          git submodule update --init --recursive

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Cache Bazel
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/bazel
            ~/.cache/bazelisk
          key: bazel-${{ runner.os }}-${{ hashFiles('.bazelversion', 'WORKSPACE', 'MODULE.bazel', 'version.bzl', 'plugins/coder-workspace/**', 'polygerrit-ui/**', 'java/**', 'lib/**') }}
          restore-keys: |
            bazel-${{ runner.os }}-

      - name: Install Bazelisk
        run: |
          sudo mkdir -p /usr/local/bin
          curl -L https://github.com/bazelbuild/bazelisk/releases/latest/download/bazelisk-linux-amd64 -o /tmp/bazelisk
          sudo install /tmp/bazelisk /usr/local/bin/bazel
          bazel version

      - name: Build plugin jar
        working-directory: ${{ env.GERRIT_DIR }}
        run: |
          # Copy our plugin into the freshly cloned Gerrit tree
          mkdir -p "plugins/coder-workspace"
          rsync -a --delete --exclude '.git/' --exclude '.github/' "${{ github.workspace }}/" "plugins/coder-workspace/"
          bazel build plugins/coder-workspace:coder-workspace

      - name: Prepare artifacts
        working-directory: ${{ env.GERRIT_DIR }}
        run: |
          mkdir -p dist
          cp bazel-bin/plugins/coder-workspace/coder-workspace.jar dist/coder-workspace-${{ github.ref_name }}.jar
          (cd dist && sha256sum *.jar > SHA256SUMS.txt)

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: coder-workspace-${{ github.ref_name }}
          path: ${{ env.GERRIT_DIR }}/dist/*

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GITHUB_TOKEN: ${{ secrets.GERRIT_CODER_TOKEN }}
        with:
          files: |
            ${{ env.GERRIT_DIR }}/dist/coder-workspace-${{ github.ref_name }}.jar
            ${{ env.GERRIT_DIR }}/dist/SHA256SUMS.txt
          generate_release_notes: true
          draft: false
          prerelease: ${{ contains(github.ref_name, 'rc') || contains(github.ref_name, 'beta') || contains(github.ref_name, 'alpha') }}
